backend:
  name: proxy
  proxy_url: /api/cms

media_folder: public/images/uploads
public_folder: /images/uploads

editor:
  preview: true

collections:
  - name: "intelligence"
    label: "Intelligence Articles"
    folder: "content/intelligence"
    create: true
    update: true
    delete: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "ID", name: "id", widget: "string"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Brand", name: "brand", widget: "string"}
      - {label: "Category", name: "category", widget: "select", options: ["market_analysis", "technology", "policy", "industry_news", "financial", "supply_chain"]}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Summary", name: "summary", widget: "text"}
      - {label: "Featured Image", name: "featured_image", widget: "image", required: false}
      - {label: "Content", name: "body", widget: "markdown"}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Read Time", name: "read_time", widget: "number", value_type: "int", min: 1, max: 60}
      - {label: "Importance", name: "importance", widget: "select", options: ["high", "medium", "low"]}
      - {label: "Publish Status", name: "status", widget: "select", options: ["draft", "published", "archived"], default: "draft"}
      - {label: "SEO Title", name: "seo_title", widget: "string", required: false}
      - {label: "SEO Description", name: "seo_description", widget: "text", required: false}
      - {label: "Related Links", name: "related_links", widget: "list", required: false, fields: [{label: "Title", name: "title", widget: "string"}, {label: "URL", name: "url", widget: "string"}]}
      - {label: "Data Source", name: "data_source", widget: "string", required: false}
      - {label: "Featured Article", name: "featured", widget: "boolean", default: false}

  - name: "models"
    label: "Vehicle Models"
    folder: "content/models"
    create: true
    update: true
    delete: true
    slug: "{{brand}}-{{model_name}}"
    fields:
      - { label: "ID", name: "id", widget: "string" }
      - { label: "Brand", name: "brand", widget: "select", options: ["NIO", "BYD", "Tesla", "Li Auto", "XPeng", "ZEEKR", "AITO", "Xiaomi", "Other"] }
      - { label: "Model Name", name: "model_name", widget: "string" }
      - { label: "Status", name: "status", widget: "select", options: ["active", "discontinued", "upcoming", "concept"] }
      - { label: "Main Image", name: "image", widget: "image" }
      - { label: "Image Gallery", name: "gallery", widget: "list", field: {label: "Image", name: "image", widget: "image"}, required: false }
      - { label: "Price Range", name: "price_range", widget: "string" }
      - { label: "Starting Price", name: "starting_price", widget: "number", value_type: "float", required: false }
      - { label: "Vehicle Category", name: "category", widget: "select", options: ["Sedan", "SUV", "MPV", "Sports Car", "Pickup", "Other"] }
      - { label: "Drivetrain", name: "drivetrain", widget: "select", options: ["FWD", "RWD", "AWD"], required: false }
      - { label: "Range (km)", name: "range", widget: "number", value_type: "int", required: false }
      - { label: "Battery Capacity (kWh)", name: "battery_capacity", widget: "number", value_type: "float", required: false }
      - { label: "Max Power (kW)", name: "max_power", widget: "number", value_type: "int", required: false }
      - { label: "0-100km/h Acceleration (s)", name: "acceleration", widget: "number", value_type: "float", required: false }
      - { label: "Seats", name: "seats", widget: "number", value_type: "int", min: 2, max: 9, required: false }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Detailed Specifications", name: "specifications", widget: "markdown", required: false }
      - { label: "Launch Date", name: "launch_date", widget: "datetime" }
      - { label: "Updated Date", name: "updated_date", widget: "datetime", required: false }
      - { label: "Features", name: "features", widget: "list", required: false }
      - { label: "Competitors", name: "competitors", widget: "list", required: false }
      - { label: "Market Performance", name: "market_performance", widget: "text", required: false }